[package]
name = "massa-sc-runtime"
version = "0.10.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = "=1.0"
serde_json = "=1.0"
wasmer = { version = "=4.0.0", features = ["static-artifact-create"] }
wasmer-compiler-singlepass = "=4.0.0"
wasmer-compiler-cranelift = "=4.0.0"
wasmer-types = "=4.0.0"
wasmer-middlewares = "=4.0.0"
tracing = "0.1"
base64 = "=0.21"
serial_test = "2.0.0"
loupe = "0.1"
parking_lot = "0.12"
rand = "=0.8"
displaydoc = "0.2"
thiserror = "1.0"
chrono = { version = "=0.4", features = ["clock"], default-features = false }
sha2 = "=0.10.6"
# for gas_calibration middleware
regex = "1"
more-asserts = "0.3"
function_name = "0.3"
num_enum = "0.6"
prost = "=0.11.9"
prost-types = "=0.11.9"

[build-dependencies]
glob = "0.3.1"
prost-build = "=0.11.9"

[features]
gas_calibration = []
testing = []
dumper = []
prost-build = []
