[package]
name = "massa-sc-runtime"
version = "0.10.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
as-ffi-bindings = { git = "https://github.com/massalabs/as-ffi-bindings.git", tag = "0.5.0" }
base64 = "=0.21"
chrono = { version = "=0.4", features = ["clock"], default-features = false } 
displaydoc = "0.2"
function_name = "0.3"
loupe = "0.1"
massa-proto-rs = { git = "https://github.com/massalabs/massa-proto-rs", branch = "feature/Improve_ABI_types_in_wasmv1", features = [
    "tonic-build",
] }
more-asserts = "0.3"
num_enum = "0.6.1"
parking_lot = "0.12"
prost = "=0.11.9"
prost-types = "=0.11.9"
rand = "=0.8"
# for gas_calibration middleware
regex = "1"
serde = "=1.0"
serde_json = "=1.0"
serial_test = "2.0.0"
sha2 = "=0.10.6"
sha3 = "=0.10.8"
thiserror = "1.0"
tracing = "0.1"
wasmer = { version = "=4.0.0", features = ["static-artifact-create"] }
wasmer-compiler-cranelift = "=4.0.0"
wasmer-compiler-singlepass = "=4.0.0"
wasmer-middlewares = "=4.0.0"
wasmer-types = "=4.0.0"

[dev-dependencies]
bs58 = { version = "=0.4", features = ["check"] }

[build-dependencies]
serde = "=1.0"
serde_json = "=1.0"
which = "4.4.0"

[features]
gas_calibration = []
testing = []
dumper = []
build-wasm = []
