[package]
name = "massa-sc-runtime"
version = "0.10.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0"
wasmer = { version = "~3.1.1", features = ["static-artifact-create"] }
wasmer-compiler-singlepass = "~3.1.1"
wasmer-compiler-cranelift = "~3.1.1"
wasmer-types = "~3.1.1"
wasmer-middlewares = "~3.1.1"
tracing = "0.1"
as-ffi-bindings = { git = "https://github.com/massalabs/as-ffi-bindings.git", tag = "v0.3.3" }
base64 = "0.21"
serial_test = "1.0.0"
loupe = "0.1"
parking_lot = "0.12"
rand = "0.8"
displaydoc = "0.2"
thiserror = "1.0"
chrono = { version = "0.4", features = ["clock"], default-features = false }
massa_hash = { git = "https://github.com/massalabs/massa.git", package = "massa_hash" }
sha2 = "0.10.6"
# for gas_calibration middleware
regex = "1"
more-asserts = "0.3"
function_name = "0.3"
prost = "0.11.8" # specify the exact version to ensure determinism
num_enum = "0.5"

[build-dependencies]
prost-build = "0.11.8" # specify exact version to ensure determinism

[features]
gas_calibration = []
testing = []
dumper = []
