[package]
name = "massa-sc-runtime"
version = "0.10.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0"
wasmer = { version = "3.0" }
# as-ffi-bindings = "0.2.7"
as-ffi-bindings = { git = "https://github.com/massalabs/as-ffi-bindings.git", tag = "v0.3.0"}
wasmer-compiler-singlepass = { version = "3.0" }
wasmer-types = { version = "3.0" }
wasmer-middlewares = { version = "3.0" }
base64 = "0.13"
serial_test = "0.8"
loupe = "0.1"
parking_lot = "0.12"
rand = "0.8"
displaydoc = "0.2"
thiserror = "1.0"
# for gas_calibration middleware
regex = "1"
more-asserts = "0.3"
function_name = "0.3"

[features]
gas_calibration = []
